export const USER_DETAILS_TYPES = {
    FETCH_USER_DETAILS: 'FETCH_USER_DETAILS',
    FETCH_USER_DETAILS_SUCCESS: 'FETCH_USER_DETAILS_SUCCESS',
    FETCH_USER_DETAILS_FAILED: 'FETCH_USER_DETAILS_FAILED',
}